In [ ]:
# bài 1
# Tạo một tensor có giá trị ban đầu là 2.0
# định nghĩa hàm số và tính gradient
# y = x^3 + 2x^2 +5x + 1
# hãy tính dy/dx tại giá trị của x
# dùng phương pháp gradient descent cới learning rate alpha = 0.1 để cập nhtaaj giá trị x trong 10 vòng lập

# bài 2

# Tạo một tập dữ liệu giả lập với x là số giờ học ( ngẫu nhiên từ 1-10) và y là dố điểm được tính theo công thức 

In [ ]:
# Bài tập về nhà 1
import torch  

# Bước 1: Khởi tạo tensor x với giá trị ban đầu là 2.0 và yêu cầu tính gradient
x = torch.tensor(2.0, requires_grad=True)

# Bước 2: Định nghĩa hàm số y = x^3 + 2x^2 + 5x + 1
def function(x):
    return x**3 + 2*x**2 + 5*x + 1

# Số vòng lặp Gradient Descent
num_epochs = 10
learning_rate = 0.1

for epoch in range(num_epochs):
    y = function(x)  # Tính giá trị của hàm số
    y.backward()  # Tính đạo hàm dy/dx
    with torch.no_grad():  # Tắt tính toán gradient để cập nhật giá trị
        x -= learning_rate * x.grad  # Cập nhật x theo Gradient Descent
        x.grad.zero_()  # Reset gradient về 0 để tránh cộng dồn

    print(f"Epoch {epoch+1}: x = {x.item()}")

Epoch 1: x = -0.5
Epoch 2: x = -0.875
Epoch 3: x = -1.2546875476837158
Epoch 4: x = -1.7250847816467285
Epoch 5: x = -2.427826166152954
Epoch 6: x = -3.7249975204467773
Epoch 7: x = -6.897680282592773
Epoch 8: x = -18.912006378173828
Epoch 9: x = -119.14640808105469
Epoch 10: x = -4330.74755859375


In [6]:
# Bài tập về nhà 2
#BTVN 2 
import torch

# 1. Tạo tập dữ liệu giả lập
torch.manual_seed(42)  # Đặt seed để tái tạo kết quả
x = torch.randint(1, 11, (20,)).float()  # 20 giá trị ngẫu nhiên từ 1 đến 10
noise = torch.randn(20) * 0.5  # Noise nhỏ
y = 3 * x + 5 + noise  # Công thức y = 3x + 5 + noise

# 2. Khởi tạo tham số w, b ngẫu nhiên
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# 3. Định nghĩa hàm tính MSE (Mean Squared Error)
def compute_loss(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

# 4. Gradient Descent với learning rate alpha = 0.01
learning_rate = 0.01
epochs = 100

for epoch in range(epochs):
    # Dự đoán giá trị y
    y_pred = w * x + b  
    loss = compute_loss(y_pred, y)  # Tính MSE
    
    # 5. Tính gradient
    loss.backward()  
    
    # 6. Cập nhật tham số
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        # Đặt gradient về 0 để tránh cộng dồn
        w.grad.zero_()
        b.grad.zero_()
    
    # 7. In loss mỗi 10 vòng để quan sát sự hội tụ
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item()}, w = {w.item()}, b = {b.item()}")

# 8. Hiển thị kết quả cuối cùng
print("\nFinal parameters:")
print(f"w = {w.item()}, b = {b.item()}")


Epoch 10: Loss = 3.5481667518615723, w = 3.616509199142456, b = 1.2902840375900269
Epoch 20: Loss = 3.3145415782928467, w = 3.591973066329956, b = 1.4407070875167847
Epoch 30: Loss = 3.097622871398926, w = 3.5681142807006836, b = 1.585620403289795
Epoch 40: Loss = 2.8962063789367676, w = 3.54512357711792, b = 1.725259780883789
Epoch 50: Loss = 2.7091822624206543, w = 3.5229694843292236, b = 1.859817385673523
Epoch 60: Loss = 2.5355238914489746, w = 3.501621723175049, b = 1.9894779920578003
Epoch 70: Loss = 2.3742756843566895, w = 3.481050968170166, b = 2.114419937133789
Epoch 80: Loss = 2.2245490550994873, w = 3.461228609085083, b = 2.2348148822784424
Epoch 90: Loss = 2.085522413253784, w = 3.4421277046203613, b = 2.3508284091949463
Epoch 100: Loss = 1.9564313888549805, w = 3.4237220287323, b = 2.4626195430755615

Final parameters:
w = 3.4237220287323, b = 2.4626195430755615


In [8]:
# pytorch with tensor
import torch
import numpy as np
torch.__version__

'2.6.0+cpu'

In [9]:
# chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [10]:
x = torch.from_numpy(arr)
print(x)
print(x.dtype)
print(type(x))

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
torch.int32
<class 'torch.Tensor'>


In [11]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [12]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [13]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [14]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4], dtype=torch.int32)


In [15]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [16]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4], dtype=torch.int32)


In [17]:
# BTVN 3: giải thích lý do tại sao cho 2 trường hợp trên

Giải thích:

Khi sử dụng torch.tensor(arr), PyTorch tạo một bản sao mới của dữ liệu từ NumPy array.
Điều này có nghĩa là x và arr không còn liên kết với nhau.
Khi thay đổi arr[0] = 99, tensor x vẫn giữ nguyên giá trị ban đầu

In [18]:
# BTVN 4: bạn hãy giúp thầy về nhà tạo tensor với :
# Empyty
# Zeros 
# Ones 
# Random
# Reshape với view với view as

In [19]:
import torch  

# Tạo tensor rỗng (không khởi tạo giá trị)
empty_tensor = torch.empty(3, 3)
print("Empty Tensor:\n", empty_tensor)

# Tạo tensor với toàn số 0
zeros_tensor = torch.zeros(3, 3)
print("\nZeros Tensor:\n", zeros_tensor)

# Tạo tensor với toàn số 1
ones_tensor = torch.ones(3, 3)
print("\nOnes Tensor:\n", ones_tensor)

# Tạo tensor với giá trị ngẫu nhiên
random_tensor = torch.rand(3, 3)
print("\nRandom Tensor:\n", random_tensor)

# Thay đổi kích thước tensor bằng view()  
tensor = torch.arange(9)  # Tạo tensor 1D từ 0-8
reshaped_tensor = tensor.view(3, 3)  # Chuyển thành 3x3
print("\nTensor sau view(3,3):\n", reshaped_tensor)

# Thay đổi kích thước tensor bằng view_as()  
another_tensor = torch.zeros_like(reshaped_tensor)  # Tạo tensor có cùng kích thước
view_as_tensor = tensor.view_as(another_tensor)  # Chuyển tensor về cùng shape
print("\nTensor sau view_as:\n", view_as_tensor)


Empty Tensor:
 tensor([[-1.5099e-31,  7.3568e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Random Tensor:
 tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958],
        [0.9147, 0.2036, 0.2018]])

Tensor sau view(3,3):
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Tensor sau view_as:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
